export const FETCH_COIN_DETAILS = "FETCH_COIN_DETAILS";
export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS";
export const FETCH_COIN_DETAILS_FAILED = "FETCH_COIN_DETAILS_FAILED";

export const SEARCH_COINS = "SEARCH_COINS";

export const SAVE_FAVORITE = "SAVE_FAVORITE";

export const DELETE_FAVORITE = "DELETE_FAVORITE";

export const SORT_LIST = "SORT_LIST";

export const FETCH_SECONDARY_LIST = "FETCH_SECONDARY_LIST";
export const FETCH_SECONDARY_LIST_SUCCESS = "FETCH_SECONDARY_LIST_SUCCESS";
export const FETCH_SECONDARY_LIST_FAILED = "FETCH_SECONDARY_LIST_FAILED";